- README.md
- roles/maintenance_10_linux/tasks/main.yml
> docs: clarify that failing tasks are expected under certain circumstances

- README.md
> Add example output to readme and fix ci badge

- README.md
- roles/maintenance_11_debian/tasks/main.yml
> fix: Add missing dash to ignore the template task and update readme

- roles/maintenance_10_linux/tasks/main.yml
> fix(10-039): remove broken journald.conf parsing, only rely on journal mtime

- README.md
- roles/maintenance_10_linux/tasks/main.yml
- roles/maintenance_11_debian/tasks/main.yml
- roles/maintenance_15_rhel/tasks/main.yml
As reported by @beatrubi as #22 in our internal issue tracker.
> refactor: replace injected ansible_ facts by ansible_facts

- roles/maintenance_15_rhel/vars/rhel_8.yml
- roles/maintenance_15_rhel/vars/rhel_9.yml
Add the two minimal repos, BaseOS and AppStream, to the verification.
> feat: add basic repos for RHEL 8 & 9

- roles/maintenance_10_linux/tasks/main.yml
> fix(10-050): postfix task could no longer be excluded

- README.md
See https://docs.ansible.com/ansible/latest/reference_appendices/config.html#callbacks-enabled
Reported internally as #34
> Fix typo in example ansible.cfg

- roles/maintenance_12_ubuntu/README.md
- roles/maintenance_12_ubuntu/defaults/main.yml
- roles/maintenance_12_ubuntu/tasks/main.yml
This PR implements the Role for Ubuntu.
> implement ubuntu checklist

- plugins/callback/report.py
Fixes internal issue #33.
Also fixes #17.
Emits the following output:
```
- [~] skipped
```
This style of tri-stating is taken from Gitlab-flavored Markdown, which [recently introduced tri-state checkboxes](https://gitlab.com/gitlab-org/gitlab/-/merge_requests/85982). Gitlab renders this like this:
> feat(report): implement tristate checklist and show indeterminate state

- roles/maintenance_10_linux/tasks/main.yml
> fix(10-034): jinja error in debug.

- roles/maintenance_15_rhel/tasks/main.yml
> 15-011: yum check-update fails when error status is wrong

- plugins/modules/lastlogins.py
- roles/maintenance_10_linux/defaults/main.yml
- roles/maintenance_10_linux/tasks/main.yml
> feat(10_linux): Add time window to "last" invocation.

- plugins/modules/find.py
- roles/maintenance_10_linux/tasks/main.yml
@adf-patrickha please test whether this fixes your issue.
> Fix cross-mountpoint pruning when searching for large logfiles

- plugins/callback/report.py
create a new optional task var `todo: true`.
When `todo: true` is set, the task is shown as unchecked in the checklist, even when the ansible task is OK.
That allows us to easily add tasks in the maintenance-collection which can't be check with ansible. It could also be solved by using `changed_when: true` but that would mean that it shows up in the Ansible-Tasklist which we don't necessarily want.
Example:
```yaml
- <<: *task
vars:
taskid: 10-006
name: "Preparation: Discuss and confirm maintenance with Service Manager if applicable."
todo: true
ansible.builtin.service_facts: {}
```
It's still not very clean (e.g. the `ansible.builtin.service_facts: {}` hack to get a `noop-task`) but IMO better than
```yaml
- <<: *task
vars:
taskid: 10-006
name: "Preparation: Discuss and confirm …
```
> Add feature to create 'always-unchecked' task

- roles/maintenance_10_linux/defaults/main.yml
- roles/maintenance_10_linux/tasks/main.yml
- roles/maintenance_10_linux/vars/Debian.yml
- roles/maintenance_10_linux/vars/RedHat.yml
Create new task_id 10-037 : Disk: logrotate: Are there files in /var/log that are not rotated? 
This task must be tested before validation
> 10-037 logrotate

- galaxy.yml
- roles/maintenance_31_nginx/README.md
- roles/maintenance_31_nginx/defaults/main.yml
- roles/maintenance_31_nginx/tasks/main.yml
Implementing the first basic set of checks for 31_nginx
> feat: maintenance_31_nginx

- roles/maintenance_10_linux/defaults/main.yml
- roles/maintenance_10_linux/tasks/main.yml
Progressing with [Gitlab #40](https://git.adfinis.com/ch-classicit/maintenance-ansible-automation/-/issues/40)
> fix(10-035): excluded /var/log from check 10-035

- roles/maintenance_12_ubuntu/tasks/main.yml
Fixing [#51](https://git.adfinis.com/ch-classicit/maintenance-ansible-automation/-/issues/51)
> fix: typo leading to duplicated 12-012

- README.md
> docs: clarify that python 3 must be used
